/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import javax.swing.JOptionPane;

public class window extends javax.swing.JFrame {

    code code = new code();

    
    public window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        item3 = new javax.swing.JLabel();
        item1 = new javax.swing.JLabel();
        item2 = new javax.swing.JLabel();
        item5 = new javax.swing.JLabel();
        item4 = new javax.swing.JLabel();
        mensaje1 = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        mensajeU = new javax.swing.JLabel();
        rules = new javax.swing.JButton();
        userOP = new javax.swing.JSlider();
        mensaje2 = new javax.swing.JLabel();
        lanzar = new javax.swing.JButton();
        eleccionPC = new javax.swing.JLabel();
        eleccionUser = new javax.swing.JLabel();
        mensajeP = new javax.swing.JLabel();
        mensaje3 = new javax.swing.JLabel();
        resultadoU = new javax.swing.JLabel();
        resultadoP = new javax.swing.JLabel();
        btnFin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 123, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        item3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/img/2.1.png"))); // NOI18N

        item1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/img/1.1.png"))); // NOI18N

        item2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/img/4.1.png"))); // NOI18N

        item5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/img/3.1.png"))); // NOI18N

        item4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/img/5.1.png"))); // NOI18N

        mensaje1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        mensaje1.setText("¡Escoge tu movimiento!");

        btnInicio.setBackground(new java.awt.Color(0, 0, 0));
        btnInicio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(51, 204, 0));
        btnInicio.setText("Play Game");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        mensajeU.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        mensajeU.setText("USER");

        rules.setBackground(new java.awt.Color(0, 0, 0));
        rules.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rules.setForeground(new java.awt.Color(255, 255, 255));
        rules.setText("Rules");
        rules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesActionPerformed(evt);
            }
        });

        userOP.setMajorTickSpacing(1);
        userOP.setMaximum(5);
        userOP.setMinimum(1);
        userOP.setMinorTickSpacing(1);
        userOP.setPaintLabels(true);
        userOP.setPaintTicks(true);
        userOP.setValue(1);

        mensaje2.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 48)); // NOI18N
        mensaje2.setText("VS");

        lanzar.setBackground(new java.awt.Color(0, 0, 0));
        lanzar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lanzar.setForeground(new java.awt.Color(255, 255, 255));
        lanzar.setText("¡Lanzar!");
        lanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanzarActionPerformed(evt);
            }
        });

        eleccionPC.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 48)); // NOI18N
        eleccionPC.setText("ㅤ");

        eleccionUser.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 48)); // NOI18N
        eleccionUser.setText("ㅤ");

        mensajeP.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        mensajeP.setText("PC");

        mensaje3.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        mensaje3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensaje3.setText(";-;");

        resultadoU.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        resultadoU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultadoU.setText("( )");

        resultadoP.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        resultadoP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultadoP.setText("( )");

        btnFin.setBackground(new java.awt.Color(0, 0, 0));
        btnFin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFin.setForeground(new java.awt.Color(255, 255, 255));
        btnFin.setText("End");
        btnFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mensaje1)
                .addGap(277, 277, 277))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(item1)
                        .addGap(65, 65, 65)
                        .addComponent(item2)
                        .addGap(78, 78, 78)
                        .addComponent(item3)
                        .addGap(66, 66, 66)
                        .addComponent(item4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(item5)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rules)
                        .addGap(294, 294, 294)
                        .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFin)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(mensajeU))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(eleccionUser, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(lanzar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(mensaje2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eleccionPC, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(mensajeP)
                                .addGap(54, 54, 54)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(userOP, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(resultadoU, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addComponent(mensaje3, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(resultadoP, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFin)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rules)
                        .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(mensaje1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(item3)
                            .addComponent(item4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(item1)
                            .addComponent(item5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(userOP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(eleccionUser, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eleccionPC, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(resultadoU)
                                    .addComponent(resultadoP)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lanzar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mensajeP)
                                    .addComponent(mensajeU))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mensaje2)
                                .addGap(108, 108, 108)
                                .addComponent(mensaje3)))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(item2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        item3.setVisible(false);
        item1.setVisible(false);
        item2.setVisible(false);
        item5.setVisible(false);
        item4.setVisible(false);
        mensaje1.setVisible(false);
        mensajeU.setVisible(false);
        userOP.setVisible(false);
        mensaje2.setVisible(false);
        lanzar.setVisible(false);
        eleccionPC.setVisible(false);
        eleccionUser.setVisible(false);
        mensajeP.setVisible(false);
        mensaje3.setVisible(false);
        resultadoU.setVisible(false);
        resultadoP.setVisible(false);
        btnFin.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        code.botonInicio();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void rulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulesActionPerformed
        JOptionPane.showMessageDialog(null, 
                " La piedra aplasta la tijera\n" +
                " La piedra machaca al lagarto\n" +
                " El papel envuelve la piedra\n" +
                " El papel desautoriza a Spock\n" +
                " La tijera corta el papel\n" +
                " La tijera decapita al lagarto\n" +
                " El lagarto envenena a Spock\n" +
                " El lagarto se come el papel\n" +
                " Spock rompe las tijeras\n" +                
                " Spock vaporiza la piedra");
    }//GEN-LAST:event_rulesActionPerformed

    private void lanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanzarActionPerformed
        //JOptionPane.showMessageDialog(null, String.valueOf(this.userOP.getValue()));
        code.escogerItemUser();
        code.botonLanzar();
        code.escogerItemPC();
        code.resultados();
    }//GEN-LAST:event_lanzarActionPerformed

    private void btnFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinActionPerformed
        code.finalizar();
    }//GEN-LAST:event_btnFinActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnFin;
    public static javax.swing.JButton btnInicio;
    public static javax.swing.JLabel eleccionPC;
    public static javax.swing.JLabel eleccionUser;
    public static javax.swing.JLabel item1;
    public static javax.swing.JLabel item2;
    public static javax.swing.JLabel item3;
    public static javax.swing.JLabel item4;
    public static javax.swing.JLabel item5;
    public static javax.swing.JButton lanzar;
    public static javax.swing.JLabel mensaje1;
    public static javax.swing.JLabel mensaje2;
    public static javax.swing.JLabel mensaje3;
    public static javax.swing.JLabel mensajeP;
    public static javax.swing.JLabel mensajeU;
    public static javax.swing.JLabel resultadoP;
    public static javax.swing.JLabel resultadoU;
    public static javax.swing.JButton rules;
    public static javax.swing.JSlider userOP;
    // End of variables declaration//GEN-END:variables
}
